# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 721e45b89f6119e620d42205d30b65f17dc288542970f902b20b0721c0c79524bdc52585bf9d43f39afffe768d4f027ce2509c62541d4322295f403a51c8ca73

test:
  secret_key_base: 08659b2a7d05bab7e7cfe6cf161486acb2f53db9a454b6ac672c003fddc9f8f5cc4e1ac9819ca5db8061adbb0b44a357ce59bfdde0346290da044eee9c1c5bd2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
